{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRole.name | default .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{- end }}