{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name | default .Release.Name }}
  labels:
    app: {{ .Release.Name }}
rules:
  - apiGroups:
    - ""
    - apps
    - batch
    - extensions
    - rbac.authorization.k8s.io
    resources:
    - pods
    - nodes
    - alertmanagers
    - cronjobs
    - daemonsets
    - deployments
    - endpoints
    - events
    - jobs
    - namespaces
    - nodes
    - nodes/metrics
    - nodes/proxy
    - pods
    - replicasets
    - replicationcontrollers
    - scheduledjobs
    - services
    - secrets
    - statefulsets
    - persistentvolumeclaims
    - resourcequotas
    - clusterroles
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - collectord.io
    resources:
    - splunkoutputs
    - configurations
    verbs:
    - get
    - list
    - watch
  - nonResourceURLs:
    - /metrics
    verbs:
    - get
    apiGroups: []
    resources: []
  {{- if .Values.clusterRole.rules -}}
    {{ toYaml .Values.clusterRole.rules | nindent 2 -}}
  {{- end }}
{{- end }}