{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/weight": "-90"
  name: {{ .Values.serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}